# Starts the Auto Scaling Group  for ActiveMq (behind a load balancer for HA)
# ***** NEED pre-existing custom AMI for this *****

- hosts: localhost
  gather_facts: no
  vars: 
     region: us-east-1
     keypair_name: kops-microservices-demo
     security_group_name: active-mq-security-group
     instance_type: t2.nano
     image_id: ami-051585d8bbc21f711

  tasks:
  - name: Setup security group for ActiveMq
    ec2_group:
      name: "{{ security_group_name }}"
      description: Security rules
      region: "{{ region }}"
      rules_egress:
          - proto: tcp
            from_port: 0
            to_port: 65535
            cidr_ip: 0.0.0.0/0
      rules:
         - proto: tcp
           from_port: 8161
           to_port: 8161
           cidr_ip: 0.0.0.0/0

         - proto: tcp
           from_port: 61616
           to_port: 61616
           cidr_ip: 0.0.0.0/0

         - proto: tcp
           from_port: 22
           to_port: 22
           cidr_ip: 0.0.0.0/0
    register: config_security



  - name: Setup Launch Configuration for ActiveMQ AMI
    ec2_lc:
       name: ActiveMq-Launch-Config
       image_id: "{{ image_id }}"
       key_name: "{{ keypair_name }}"
       region: "{{ region }}"
       security_groups: "{{ config_security.group_id }}"
       instance_type: "{{ instance_type }}"

  - name: Start ActiveMq ASG
    ec2_asg:
       name: ActiveMq-ASG
       region: "{{ region }}"
       availability_zones: [ "{{ region }}b" ]
       launch_config_name: "ActiveMq-Launch-Config"
       min_size: 1
       max_size: 1
       tags:
          - Name: "ActiveMq"
       load_balancers: [ 'activemq-elb' ]
